### ISSUE TITLE
Directions are not intuitive and leads to errors

### ISSUE THREAD

**Issue by byojelly** [learn-co-curriculum/using-bundler#48]
After the section "Anatomy of Bundler Files" is the Gemfile section for the lab. The directions say to add the following code to your Gemfile and then to run the test suite using rspec or learn in your terminal. The terminal yields an error. 

The order of directions leads to errors because we have not yet defined any code in our environment.rb file or the run.rb file.

I feel these directions should be modified so that the user is told to run rspec or learn at a later stage.

**Comment by aviflombaum** [comment]
I don't think this is accurate @byojelly. You can have this in your Gemfile:

```ruby
source "https://rubygems.org"

gem "sinatra"

group :development do
  gem "pry"
end
```

And the output I get is:

```
Failures:

  1) Bundler Gemfile should list the sinatra gem with the specific version 1.4.4
     Failure/Error: expect(@gemfile_text =~ /gem .sinatra., .v?1\.4\.4./).not_to eq(nil)
     
       expected: value != nil
            got: nil
     
       (compared using ==)
     # ./spec/bundler_spec.rb:32:in `block (3 levels) in <top (required)>'
```

And additional failures relating to gems being missing and versions being missing, which is the point, you add them in.
